# Path to epimodel-data directory
data_dir: data

# Replace with the actual channel (non-public)
foretold_channel: SECRET

### GLEAM

# data/sims subdirectory of gleamviz
gleamviz_sims_dir: ~/GLEAMviz/data/sims/

# Subsampling of imported data (see Pandas `df.resample`)
gleam_resample: 7D

### Extra data for web_export, relative to data_dir
web_export:
 john_hopkins: johns-hopkins.csv
 foretold: foretold.csv
 rates: rates.csv

### Upload settings
gs_prefix: "gs://static-covid/static/"
gs_url_prefix: "https://storage.googleapis.com/static-covid/static/"

### Output directory for exported data
output_dir: out/

### List of exported regions code
export_regions:
  - AF
  - AL
  - DZ
  - AO
  - AG
  - AR
  - AM
  - AU
  - AT
  - AZ
  - BD
  - BY
  - BE
  - BZ
  - BJ
  - BT
  - BO
  - BA
  - BR
  - BN
  - BG
  - BF
  - KH
  - CM
  - CA
  - TD
  - CL
  - CN
  - CO
  - CD
  - CG
  - CR
  - CI
  - HR
  - CU
  - CY
  - CZ
  - DK
  - DO
  - EC
  - EG
  - GQ
  - ER
  - EE
  - ET
  - FJ
  - FI
  - FR
  - GA
  - GE
  - DE
  - GH
  - GR
  - GU
  - GT
  - GG
  - GY
  - HT
  - HN
  - HU
  - IS
  - IN
  - ID
  - IR
  - IQ
  - IE
  - IM
  - IL
  - IT
  - JM
  - JP
  - JO
  - KZ
  - KE
  - KW
  - KG
  - LV
  - LB
  - LR
  - LT
  - LU
  - MK
  - MG
  - MY
  - MV
  - MT
  - MR
  - MU
  - MX
  - MD
  - MC
  - MN
  - ME
  - MA
  - NA
  - NP
  - NL
  - NZ
  - NI
  - NE
  - NG
  - MP
  - "NO"
  - OM
  - PK
  - PA
  - PG
  - PY
  - PE
  - PH
  - PL
  - PT
  - PR
  - QA
  - RO
  - RU
  - RW
  - SA
  - SN
  - RS
  - SC
  - SG
  - SK
  - SI
  - SO
  - ZA
  - KR
  - ES
  - LK
  - SD
  - SR
  - SV
  - SE
  - CH
  - TZ
  - TH
  - TG
  - TT
  - TN
  - TR
  - UG
  - UA
  - AE
  - GB
  - US
  - UY
  - UZ
  - VE
  - VN
  - ZM
  - ZW

